name: MythofyTeams
version: '${project.version}'
main: org.mythofy.mythofyteams.MythofyTeams
api-version: '1.20'
commands:
  team:
    description: Team commands
    usage: /team <create|invite|leave|chat|accept|deny|list|ally|neutral|enemy|allyaccept|allydeny|pvptoggle|allypvptoggle|allypvptoggleaccept|allypvptoggledeny>
    aliases: [t]