name: MythofyTeams
version: '1.0'
main: org.mythofy.mythofyteams.MythofyTeams
api-version: '1.20'
commands:
  team:
    description: Team commands
    usage: /team <create|invite|leave|chat>
    aliases: [t]